### ISSUE TITLE
option to remove tab key from confirmkeys

### ISSUE THREAD

**Issue by weijar** [alexchee/atom-inline-autocomplete#15]
I want to use tab key to cycle through words (like sublimetext):

```cson
'atom-text-editor:not([mini])':
  'tab': 'inline-autocomplete:cycle'
```

But it does not work unless remove tab key from confirmKeys list.

**Comment by weijar** [comment]
I found the default escape shortcut key may conflict with atom's multi-edit feature, whitch use escape to cancel the editing mode.

**Comment by alexchee** [comment]
I think #22 should fix this. should be up in next version 1.0.2
